// ignore_for_file: deprecated_member_use

import 'package:flutter/material.dart';
import 'package:geocoding/geocoding.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../../../../core/di/service_locator.dart';
import '../../../../core/extensions/app_localizations_x.dart';
import '../../../../core/utils/app_colors.dart';
import '../../../../core/utils/assets.dart';
import '../../../../core/utils/currency_helper.dart';
import '../../../../core/widgets/location_picker_page.dart';
import '../../../../core/widgets/status/empty_state.dart';
import '../../../../l10n/app_localizations.dart';
import '../../../account/data/datasources/saved_addresses_local_datasource.dart';
import '../../../account/data/models/saved_address_model.dart';
import '../../../account/presentation/pages/addresses_page.dart';
import '../../domain/entities/cart_item_entity.dart';
import '../../domain/services/cart_badge_controller.dart';
import '../../domain/repositories/cart_repository.dart';
import '../../domain/usecases/calculate_shipping_usecase.dart';
import '../../../auth/domain/entities/user_entity.dart';
import '../../../auth/domain/usecases/get_current_user_usecase.dart';
import '../../../orders/domain/exceptions/checkout_exception.dart';
import '../../../orders/domain/repositories/orders_repository.dart';
import '../../../orders/presentation/pages/payment_webview_page.dart';

part 'cart_checkout_page_parts/cart_checkout_page.dart';
part 'cart_checkout_page_parts/cart_checkout_page_state.dart';
part 'cart_checkout_page_parts/checkout_header.dart';
part 'cart_checkout_page_parts/header_button.dart';
part 'cart_checkout_page_parts/checkout_status_card.dart';
part 'cart_checkout_page_parts/checkout_store_group.dart';
part 'cart_checkout_page_parts/store_order_section.dart';
part 'cart_checkout_page_parts/checkout_item_tile.dart';
part 'cart_checkout_page_parts/product_thumb.dart';
part 'cart_checkout_page_parts/payment_methods_panel.dart';
part 'cart_checkout_page_parts/payment_method.dart';
part 'cart_checkout_page_parts/payment_tile.dart';
part 'cart_checkout_page_parts/phone_input_panel.dart';
part 'cart_checkout_page_parts/saved_addresses_panel.dart';
part 'cart_checkout_page_parts/saved_address_tile.dart';
part 'cart_checkout_page_parts/delivery_location_panel.dart';
part 'cart_checkout_page_parts/delivery_location_panel_state.dart';
part 'cart_checkout_page_parts/totals_panel.dart';
part 'cart_checkout_page_parts/panel.dart';
part 'cart_checkout_page_parts/total_line.dart';
part 'cart_checkout_page_parts/checkout_action_bar.dart';
