// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Y39ULVQjy8DSYq7OdMgxc-KFAQ0R0eI',
    appId: '1:263444450427:web:6c3e95f122f11cbe14a6de',
    messagingSenderId: '263444450427',
    projectId: 'bs6a-app',
    authDomain: 'bs6a-app.firebaseapp.com',
    storageBucket: 'bs6a-app.firebasestorage.app',
    measurementId: 'G-C2MZB7KKGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFEBtTicg-1ViMWxgTlUEhHxL6Vie1Io',
    appId: '1:263444450427:android:f03a4cdb078eff4714a6de',
    messagingSenderId: '263444450427',
    projectId: 'bs6a-app',
    storageBucket: 'bs6a-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1p_VNgJhs61PfBtZwKsTNas31NQLpwPk',
    appId: '1:263444450427:ios:013852f9cdd721c914a6de',
    messagingSenderId: '263444450427',
    projectId: 'bs6a-app',
    storageBucket: 'bs6a-app.firebasestorage.app',
    iosBundleId: 'com.example.ionbitECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1p_VNgJhs61PfBtZwKsTNas31NQLpwPk',
    appId: '1:263444450427:ios:013852f9cdd721c914a6de',
    messagingSenderId: '263444450427',
    projectId: 'bs6a-app',
    storageBucket: 'bs6a-app.firebasestorage.app',
    iosBundleId: 'com.example.ionbitECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Y39ULVQjy8DSYq7OdMgxc-KFAQ0R0eI',
    appId: '1:263444450427:web:0151952837b58de614a6de',
    messagingSenderId: '263444450427',
    projectId: 'bs6a-app',
    authDomain: 'bs6a-app.firebaseapp.com',
    storageBucket: 'bs6a-app.firebasestorage.app',
    measurementId: 'G-Y781HRL9FT',
  );
}
